spring:
  application:
    name: CurrencyGateway
  profiles:
    active: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/currency_info_gateway
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:test}
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          show_sql: false
          use_sql_comments: true
          format_sql: true
          type: trace
  logging:
    level:
      org.hibernate: TRACE

currency-gateway:
  fixer:
    apiAccessKey: ${FIXER_API_ACCESS_KEY:test}
    baseUrl: http://data.fixer.io/api
    latestRatesUrl: /latest
    currenciesUrl: /symbols
  schedules:
    rates-collector: "0 0 0,12 * * ?"