spring:
  profiles:
    active: local

currency-gateway:
  fixer:
    apiAccessKey: ${FIXER_API_ACCESS_KEY:test}
    baseUrl: http://data.fixer.io/api
    latestRatesUrl: /latest
    currenciesUrl: /symbols
  schedules:
#    run twice a day, at midnight and at noon, every day
    rates-collector: "0 0 0,12 * * ?" 