spring:
  profiles:
    active: local

currency-gateway:
  fixer:
    api-access-key: ${FIXER_API_ACCESS_KEY:test}
    base-url: http://data.fixer.io/api
    latest-rates-url: /latest
    currencies-url: /symbols
  schedules:
#    run twice a day, at midnight and at noon, every day
    rates-collector: "0 0 0,12 * * ?" 