spring:
  application:
    name: CurrencyGateway
  profiles:
    active: mysql
  data:
    redis:
      url: redis://localhost:6379
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/currency_info_gateway
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          show_sql: false
          use_sql_comments: true
          format_sql: true
          type: trace
  logging:
    level:
      org.hibernate: TRACE
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: amq.topic
      routingKey: currency.gateway.api-requests
      receiveQueue: api-requests-queue

currency-gateway:
  fixer:
    apiAccessKey: ${FIXER_API_ACCESS_KEY}
    baseUrl: http://data.fixer.io/api
    latestRatesUrl: /latest
    currenciesUrl: /symbols
  schedules:
    rates-collector: "0 0 0,12 * * ?"